server:
  port: 19095

spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

service:
  jwt:
    access-expiration: 3600000
    secreat-key: "3UMzr1agWuUOpd2Ypm1BfGv3c7GLj0l3ToEYrAk/GXvQVmOyG27VVZ6tAhYHg+pubxhLYLO/ACcbpoEYo++Cjg=="

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
